### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by ntonnaett** [SpotlightKid/jack-matchmaker#17] opened 2021-01-22 14:20 UTC
We run jack-matchmaker as a systemd service. After some time it crashed with a segfault. Other jack clients are not affected.
I don't know how to debug this.

> [11557.773032] jack-matchmaker[1155]: segfault at 4 ip 00007f4c0d44b2ce sp 00007f4c0d0f2c50 error 4 in libjack.so.0.1.0[7f4c0d427000+28000]
[11557.773039] Code: ba 03 00 00 00 31 ff be 0c 00 00 00 e8 7b d2 fd ff 48 89 85 08 01 00 00 48 85 c0 0f 84 bb 00 00 00 80 bd 10 01 00 00 00 75 0a <44> 0f b6 60 05 45 84 e4 75 48 41 bc 01 00 00 00 48 83 c4 08 44 89
[12995.735951] jack-matchmaker[3759]: segfault at 4 ip 00007f998a4a92ce sp 00007ffcf9cfb3a0 error 4 in libjack.so.0.1.0[7f998a485000+28000]
[12995.735955] Code: ba 03 00 00 00 31 ff be 0c 00 00 00 e8 7b d2 fd ff 48 89 85 08 01 00 00 48 85 c0 0f 84 bb 00 00 00 80 bd 10 01 00 00 00 75 0a <44> 0f b6 60 05 45 84 e4 75 48 41 bc 01 00 00 00 48 83 c4 08 44 89

Ubuntu 20.04.1 with 5.4.0-62-lowlatency kernel

**Comment by SpotlightKid** [comment] 2021-01-22 20:13
Hi, thanks for the error report. Does this mean this happened once only or does this happen regularly? And can you reproduce the conditions under which this happens? If yes, what are they?

Can you specify:

* the version of jack you are running
* whether you run jackd or jackdbus
* and what settings, i.e. frames/period, nperiod, which MIDI driver, etc.
* the contents of your `/etc/conf.d/jack-matchmaker` file.

Lastly, you can edit `/etc/conf.d/jack-matchmaker` and add a line with `VERBOSITY=DEBUG` and restart the service. If it crashes again, look at the log output with `journalctl --user -u jack-matchmaker` and report it here. Maybe this helps to see when exactly it crashes.

**Comment by SpotlightKid** [comment] 2021-02-01 05:33
Closing due to lacking feedback.

**Closed as completed by SpotlightKid** 2021-02-01 05:33 UTC
Labels: bug, needs feedback
